import Link from "next/link";

export default function Home() {
  return (
    <div className="dark flex min-h-screen items-center justify-center bg-zinc-50 font-sans dark:bg-black">
      <main className="flex min-h-screen w-full max-w-3xl flex-col items-center justify-center gap-6 px-6 text-center sm:px-10">
        <span className="rounded-full bg-zinc-100 px-4 py-1 text-xs font-medium uppercase tracking-wide text-zinc-700 dark:bg-zinc-900 dark:text-zinc-300">
          Created with better-ts-stack
        </span>
        <h1 className="text-3xl font-semibold leading-tight tracking-tight text-black dark:text-zinc-50 sm:text-4xl">
          Your new TypeScript stack is ready.
        </h1>
        <p className="max-w-xl text-sm leading-relaxed text-zinc-600 dark:text-zinc-400 sm:text-base">
          This application was generated by{" "}
          <span className="font-semibold text-zinc-900 dark:text-zinc-50">
            better-ts-stack
          </span>
          . Start by editing{" "}
          <code className="rounded bg-zinc-100 px-1.5 py-0.5 text-xs font-mono text-zinc-800 dark:bg-zinc-900 dark:text-zinc-200">
            app/page.tsx
          </code>{" "}
          and wiring up your API, database, and auth flows.
        </p>
        <div className="mt-4 flex flex-col gap-3 text-sm font-medium sm:flex-row">
          <Link
            className="flex h-10 items-center justify-center rounded-full bg-black px-6 text-white transition-colors hover:bg-zinc-800 dark:bg-zinc-100 dark:text-black dark:hover:bg-zinc-300"
            href="https://github.com/Abdullah-dev0/better-ts-stack"
            target="_blank"
            rel="noreferrer"
          >
            View better-ts-stack docs
          </Link>
          <a
            className="flex h-10 items-center justify-center rounded-full border border-zinc-300 px-6 text-zinc-800 transition-colors hover:bg-zinc-100 dark:border-zinc-700 dark:text-zinc-200 dark:hover:bg-zinc-900"
            href="https://github.com/Abdullah-dev0/better-ts-stack"
            target="_blank"
            rel="noreferrer"
          >
            Star the repo
          </a>
        </div>
      </main>
    </div>
  );
}
